apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glimpse-service-friend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: glimpse-service-friend
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "-p", "8081",
          "-a", "127.0.0.1:5000",
          "-s", "friend.glimpse.online",
          "-v", "2017-08-29r2",
        ]
        ports:
          - containerPort: 8081
      - name: friend
        image: gcr.io/glimpse-123456/glimpse-service-friend:latest
        ports:
          - containerPort: 5000
        env:
        - name: CASSANDRA_HOSTS
          value: cassandra
        - name: USER_INFO_BULK_URL
          value: http://glimpse.service.user
