apiVersion: v1
kind: Service
metadata:
  name: glimpse-service-friend
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: glimpse-service-friend
  type: LoadBalancer